name: release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  id-token: write
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::187580527878:role/GitHubSSMDeployRole
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push image
        run: |
          ECR_URI=187580527878.dkr.ecr.ap-south-1.amazonaws.com/theta-backend

          docker buildx build \
            --platform linux/amd64 \
            -t $ECR_URI:${GITHUB_REF_NAME} \
            -t $ECR_URI:latest \
            --push .

  deploy:
    needs: release
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::187580527878:role/GitHubSSMDeployRole
          aws-region: ap-south-1

      - name: Get current task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition Theta_task \
            --query taskDefinition \
            > task-def.json

      - name: Update image in task definition
        run: |
          IMAGE_URI=187580527878.dkr.ecr.ap-south-1.amazonaws.com/theta-backend:${GITHUB_REF_NAME}

          jq --arg IMAGE "$IMAGE_URI" \
            '.containerDefinitions[0].image = $IMAGE
            | del(.taskDefinitionArn,.revision,.status,.requiresAttributes,.compatibilities,.registeredAt,.registeredBy)' \
            task-def.json > new-task-def.json

      - name: Register new task definition
        run: |
          aws ecs register-task-definition \
            --cli-input-json file://new-task-def.json

      - name: Update ECS service to new revision
        run: |
          aws ecs update-service \
            --cluster Theta_cluster \
            --service Theta_task-service-nx0sgjxs \
            --task-definition Theta_task

