name: release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  id-token: write
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::187580527878:role/GitHubSSMDeployRole
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push image
        run: |
          ECR_URI=187580527878.dkr.ecr.ap-south-1.amazonaws.com/theta-backend

          docker buildx build \
            --platform linux/amd64 \
            -t $ECR_URI:${GITHUB_REF_NAME} \
            -t $ECR_URI:latest \
            --push .

  deploy:
    needs: release
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::187580527878:role/GitHubSSMDeployRole
          aws-region: ap-south-1

      - name: Force ECS deployment
        run: |
          aws ecs update-service \
            --cluster Theta-cluster \
            --service Theta_task-service-nx0sgjxs \
            --force-new-deployment
